<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Сравнение товаров");
?><?$APPLICATION->IncludeComponent("bitrix:catalog.compare.result", "template2", Array(
	"NAME" => "CATALOG_COMPARE_LIST",	// Уникальное имя для списка сравнения
		"IBLOCK_TYPE" => "catalog",	// Тип инфоблока
		"IBLOCK_ID" => "13",	// Инфоблок
		"FIELD_CODE" => array(	// Поля
			0 => "NAME",
			1 => "DETAIL_PICTURE",
		),
		"PROPERTY_CODE" => array(	// Свойства
			0 => "PODDERZHKA",
			1 => "DVD",
			2 => "RAZMER_MATRITSY_MP",
			3 => "MP3",
			4 => "BLOG_POST_ID",
			5 => "CML2_ARTICLE",
			6 => "CML2_BASE_UNIT",
			7 => "F_USER",
			8 => "BLOG_COMMENTS_CNT",
			9 => "FORUM_MESSAGE_CNT",
			10 => "vote_count",
			11 => "CML2_MANUFACTURER",
			12 => "rating",
			13 => "CML2_TRAITS",
			14 => "SORTDISCOUNT",
			15 => "CML2_TAXES",
			16 => "vote_sum",
			17 => "FORUM_TOPIC_ID",
			18 => "TIP_ZAGRUZKI",
			19 => "daygood",
			20 => "CML2_ATTRIBUTES",
			21 => "HIT",
			22 => "SORTPRICE1",
			23 => "CML2_BAR_CODE",
			24 => "VES_ZAGRUZHAEMOGO_BELYA",
			25 => "TIP_SUSHKI",
			26 => "KOLICHESTVO_KOMPLEKTOV_SHT",
			27 => "GRIL",
			28 => "KONVEKTSIYA",
			29 => "KOLICHESTVO_KONFOROK",
			30 => "ELEKTROPODZHIG",
			31 => "DUKHOVKA",
			32 => "TIP_VAROCHNOY_POVERKHNOSTI",
			33 => "TIP_UPRAVLENIYA_MIKROVOLNOVOY_PECHI",
			34 => "MOSHCHNOST_MIKROVOLN_GRILYA_VT",
			35 => "REZHIM_OBOGREVA",
			36 => "SPOSOB_NAGREVA",
			37 => "TIP_OBOGREVATELYA",
			38 => "TIP_VODONAGREVATELYA",
			39 => "TIP",
			40 => "MOSHCHNOST_VT",
			41 => "STRANA_PROIZVODITEL",
			42 => "BREND",
			43 => "TSVET",
			44 => "OBYEM_L",
			45 => "OBYEM_KHOLODILNOY_KAMERY_L",
			46 => "OBYEM_MOROZILNOY_KAMERY_L",
			47 => "KOLICHESTVO_KOMPRESSOROV",
			48 => "TIP_RAZMORAZHIVANIYA_KHOLODILNOY_KAMERY",
			49 => "TIP_RAZMORAZHIVANIYA_MOROZILNOY_KAMERY",
			50 => "KLASS_ENERGOPOTREBLENIYA",
			51 => "TEMPERATURA_V_MOROZILNOY_KAMERE",
			52 => "SHIRINA",
			53 => "VYSOTA",
			54 => "GLUBINA",
			55 => "DIAGONAL_SM",
			56 => "PODDERZHKA_USB_V_TELEVIZORE",
			57 => "PODDERZHKA_MP3",
			58 => "PODDERZHKA_DVD",
			59 => "PODDERZHKA_USB",
			60 => "CHISLO_MEGAPIKSELEY",
			61 => "SERTIFIKAT",
			62 => "TIP_UBORKI",
			63 => "TIP_PYLESBORNIKA",
			64 => "VES_VYPECHKI_G",
			65 => "KOLICHESTVO_PROGRAMM_KHLEBOPECHI",
			66 => "TIP_UPRAVLENIYA_MULTIVARKI",
			67 => "KOLICHESTVO_PROGRAMM_MULTIVARKI",
			68 => "TIP_UPRAVLENIYA_PAROVARKI",
			69 => "VOZMOZHNOST_DOLIVA_VODY",
			70 => "KOLICHESTVO_YARUSOV",
			71 => "POKRYTIE",
			72 => "PAR",
			73 => "KOLICHESTVO_SKOROSTEY",
			74 => "KOLICHESTVO_TEMPERATURNYKH_REZHIMOV",
			75 => "REZHIM_OKHLAZHDENIYA",
			76 => "IMPULSNYY_REZHIM",
			77 => "MOSHCHNOST_YOGURTNITSY_VT",
			78 => "OBSHCHEE_KOLICHESTVO_PRODUKTA_G",
			79 => "SISTEMA_PITANIYA",
			80 => "POKRYTIE_SHCHIPTSOV",
			81 => "PROIZVODITELNOST_KUB_M_CH",
			82 => "energy_class",
			83 => "good_code",
			84 => "power",
			85 => "compressors",
			86 => "",
		),
		"ELEMENT_SORT_FIELD" => "sort",	// По какому полю сортируем элементы
		"ELEMENT_SORT_ORDER" => "asc",	// Порядок сортировки элементов
		"AJAX_MODE" => "N",	// Включить режим AJAX
		"AJAX_OPTION_JUMP" => "N",	// Включить прокрутку к началу компонента
		"AJAX_OPTION_STYLE" => "Y",	// Включить подгрузку стилей
		"AJAX_OPTION_HISTORY" => "N",	// Включить эмуляцию навигации браузера
		"DETAIL_URL" => "",	// URL, ведущий на страницу с содержимым элемента раздела
		"BASKET_URL" => "/personal/cart/",	// URL, ведущий на страницу с корзиной покупателя
		"ACTION_VARIABLE" => "action",	// Название переменной, в которой передается действие
		"PRODUCT_ID_VARIABLE" => "id",	// Название переменной, в которой передается код товара для покупки
		"SECTION_ID_VARIABLE" => "SECTION_ID",	// Название переменной, в которой передается код группы
		"PRICE_CODE" => "",	// Тип цены
		"USE_PRICE_COUNT" => "N",	// Использовать вывод цен с диапазонами
		"SHOW_PRICE_COUNT" => "1",	// Выводить цены для количества
		"PRICE_VAT_INCLUDE" => "Y",	// Включать НДС в цену
		"CONVERT_CURRENCY" => "N",	// Показывать цены в одной валюте
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",	// Выводить список элементов инфоблока
		"ELEMENT_SORT_FIELD_BOX" => "name",	// По какому полю сортируем список элементов
		"ELEMENT_SORT_ORDER_BOX" => "asc",	// Порядок сортировки списка элементов
		"ELEMENT_SORT_FIELD_BOX2" => "id",	// Поле для второй сортировки списка элементов
		"ELEMENT_SORT_ORDER_BOX2" => "desc",	// Порядок второй сортировки списка элементов
		"HIDE_NOT_AVAILABLE" => "N",	// Не отображать в списке товары, которых нет на складах
		"AJAX_OPTION_ADDITIONAL" => "",	// Дополнительный идентификатор
		"OFFERS_FIELD_CODE" => array(	// Поля предложений
			0 => "",
			1 => "",
		),
		"OFFERS_PROPERTY_CODE" => array(	// Свойства предложений
			0 => "",
			1 => "",
		)
	),
	false
);?><br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>