<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("keywords", "бытовая техника, малая бытовая техника, холодильники, стиральные машины");
$APPLICATION->SetPageProperty("description", "Мы предлагаем широкий ассортимент бытовой техники по адекватным ценам.");
$APPLICATION->SetTitle("");
$filterView = (COption::GetOptionString("main", "wizard_template_id", "eshop_adapt_horizontal", SITE_ID) == "eshop_adapt_vertical" ? "HORIZONTAL" : "VERTICAL");
?><?
// по умолчанию 20 показываем
if(!$_SESSION['units']) {
	$_SESSION['units'] = 20;
}
// ecли послал запрос
elseif($_POST["units"]) {
	 $_SESSION['units'] = $_POST['units'];
}

// по умолчанию показываем по рейтингу
if(!$_SESSION['sort']) {
	$_SESSION['sort'] = "PROPERTY_rating";
    $_SESSION['order'] = "desc";
}
// ecли послал запрос
elseif($_GET["sort"]) {
	if($_GET["sort"]=="PROPERTY_rating" && $_SESSION["sort"]=="PROPERTY_rating")
		$_SESSION['order']="asc";
	elseif($_GET["sort"]=="PROPERTY_rating")
		$_SESSION['order']="desc";
	elseif($_GET["sort"]=="PROPERTY_SORTPRICE1" && $_SESSION["sort"]=="PROPERTY_SORTPRICE1")
		$_SESSION['order']="asc";
	elseif($_GET["sort"]=="PROPERTY_SORTPRICE1")
		$_SESSION['order']="desc";
	else 
		$_SESSION['order']="asc";
	
	$_SESSION['sort'] = $_GET['sort'];
}
//SORTPRICE1
// по умолчанию показываем по рейтингу
if(!$_SESSION['templ']) {
	$_SESSION['templ'] = ".default";
}
// ecли послал запрос
elseif($_GET["templ"]) {
	 $_SESSION['templ'] = $_GET['templ'];
}
?>
<?php
global $arrFilter;
$arrFilter['!CATALOG_PRICE_1'] = false;
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:catalog", 
	"template1", 
	array(
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "13",
		"HIDE_NOT_AVAILABLE" => "Y",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/catalog/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "Y",
		"USE_ELEMENT_COUNTER" => "Y",
		"USE_FILTER" => "Y",
		"FILTER_NAME" => "arrFilter",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PRICE_CODE" => array(
		),
		"FILTER_VIEW_MODE" => "VERTICAL",
		"USE_REVIEW" => "Y",
		"USE_COMPARE" => "N",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		"BASKET_URL" => "/personal/cart/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"USE_PRODUCT_QUANTITY" => "Y",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRODUCT_PROPERTIES" => array(
		),
		"SHOW_TOP_ELEMENTS" => "N",
		"SECTION_COUNT_ELEMENTS" => "N",
		"SECTION_TOP_DEPTH" => "1",
		"SECTIONS_VIEW_MODE" => "TEXT",
		"SECTIONS_SHOW_PARENT_NAME" => "N",
		"PAGE_ELEMENT_COUNT" => "\$_SESSION['units']",
		"LINE_ELEMENT_COUNT" => "4",
		"ELEMENT_SORT_FIELD" => "\$_SESSION['sort']",
		"ELEMENT_SORT_ORDER" => "desc",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER2" => "desc",
		"LIST_PROPERTY_CODE" => array(
			0 => "PODDERZHKA",
			1 => "DVD",
			2 => "RAZMER_MATRITSY_MP",
			3 => "MP3",
			4 => "CML2_ARTICLE",
			5 => "CML2_MANUFACTURER",
			6 => "rating",
			7 => "TIP_ZAGRUZKI",
			8 => "CML2_ATTRIBUTES",
			9 => "CML2_BAR_CODE",
			10 => "VES_ZAGRUZHAEMOGO_BELYA",
			11 => "TIP_SUSHKI",
			12 => "KOLICHESTVO_KOMPLEKTOV_SHT",
			13 => "GRIL",
			14 => "KONVEKTSIYA",
			15 => "KOLICHESTVO_KONFOROK",
			16 => "ELEKTROPODZHIG",
			17 => "DUKHOVKA",
			18 => "TIP_VAROCHNOY_POVERKHNOSTI",
			19 => "TIP_UPRAVLENIYA_MIKROVOLNOVOY_PECHI",
			20 => "MOSHCHNOST_MIKROVOLN_GRILYA_VT",
			21 => "REZHIM_OBOGREVA",
			22 => "SPOSOB_NAGREVA",
			23 => "TIP_OBOGREVATELYA",
			24 => "TIP_VODONAGREVATELYA",
			25 => "TIP",
			26 => "MOSHCHNOST_VT",
			27 => "STRANA_PROIZVODITEL",
			28 => "BREND",
			29 => "TSVET",
			30 => "OBYEM_L",
			31 => "OBYEM_KHOLODILNOY_KAMERY_L",
			32 => "OBYEM_MOROZILNOY_KAMERY_L",
			33 => "KOLICHESTVO_KOMPRESSOROV",
			34 => "TIP_RAZMORAZHIVANIYA_KHOLODILNOY_KAMERY",
			35 => "TIP_RAZMORAZHIVANIYA_MOROZILNOY_KAMERY",
			36 => "KLASS_ENERGOPOTREBLENIYA",
			37 => "TEMPERATURA_V_MOROZILNOY_KAMERE",
			38 => "SHIRINA",
			39 => "VYSOTA",
			40 => "GLUBINA",
			41 => "DIAGONAL_SM",
			42 => "PODDERZHKA_USB_V_TELEVIZORE",
			43 => "PODDERZHKA_MP3",
			44 => "PODDERZHKA_DVD",
			45 => "PODDERZHKA_USB",
			46 => "CHISLO_MEGAPIKSELEY",
			47 => "SERTIFIKAT",
			48 => "TIP_UBORKI",
			49 => "TIP_PYLESBORNIKA",
			50 => "VES_VYPECHKI_G",
			51 => "KOLICHESTVO_PROGRAMM_KHLEBOPECHI",
			52 => "TIP_UPRAVLENIYA_MULTIVARKI",
			53 => "KOLICHESTVO_PROGRAMM_MULTIVARKI",
			54 => "TIP_UPRAVLENIYA_PAROVARKI",
			55 => "VOZMOZHNOST_DOLIVA_VODY",
			56 => "KOLICHESTVO_YARUSOV",
			57 => "POKRYTIE",
			58 => "PAR",
			59 => "KOLICHESTVO_SKOROSTEY",
			60 => "KOLICHESTVO_TEMPERATURNYKH_REZHIMOV",
			61 => "REZHIM_OKHLAZHDENIYA",
			62 => "IMPULSNYY_REZHIM",
			63 => "MOSHCHNOST_YOGURTNITSY_VT",
			64 => "OBSHCHEE_KOLICHESTVO_PRODUKTA_G",
			65 => "SISTEMA_PITANIYA",
			66 => "POKRYTIE_SHCHIPTSOV",
			67 => "PROIZVODITELNOST_KUB_M_CH",
			68 => "price",
			69 => "NEWPRODUCT",
			70 => "SALELEADER",
			71 => "SPECIALOFFER",
			72 => "",
		),
		"INCLUDE_SUBSECTIONS" => "Y",
		"LIST_META_KEYWORDS" => "-",
		"LIST_META_DESCRIPTION" => "-",
		"LIST_BROWSER_TITLE" => "-",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "PODDERZHKA",
			1 => "DVD",
			2 => "RAZMER_MATRITSY_MP",
			3 => "MP3",
			4 => "CML2_ARTICLE",
			5 => "CML2_MANUFACTURER",
			6 => "TIP_ZAGRUZKI",
			7 => "CML2_ATTRIBUTES",
			8 => "CML2_BAR_CODE",
			9 => "VES_ZAGRUZHAEMOGO_BELYA",
			10 => "TIP_SUSHKI",
			11 => "KOLICHESTVO_KOMPLEKTOV_SHT",
			12 => "GRIL",
			13 => "KONVEKTSIYA",
			14 => "KOLICHESTVO_KONFOROK",
			15 => "ELEKTROPODZHIG",
			16 => "DUKHOVKA",
			17 => "TIP_VAROCHNOY_POVERKHNOSTI",
			18 => "TIP_UPRAVLENIYA_MIKROVOLNOVOY_PECHI",
			19 => "MOSHCHNOST_MIKROVOLN_GRILYA_VT",
			20 => "REZHIM_OBOGREVA",
			21 => "SPOSOB_NAGREVA",
			22 => "TIP_OBOGREVATELYA",
			23 => "TIP_VODONAGREVATELYA",
			24 => "TIP",
			25 => "MOSHCHNOST_VT",
			26 => "STRANA_PROIZVODITEL",
			27 => "BREND",
			28 => "TSVET",
			29 => "OBYEM_L",
			30 => "OBYEM_KHOLODILNOY_KAMERY_L",
			31 => "OBYEM_MOROZILNOY_KAMERY_L",
			32 => "KOLICHESTVO_KOMPRESSOROV",
			33 => "TIP_RAZMORAZHIVANIYA_KHOLODILNOY_KAMERY",
			34 => "TIP_RAZMORAZHIVANIYA_MOROZILNOY_KAMERY",
			35 => "KLASS_ENERGOPOTREBLENIYA",
			36 => "TEMPERATURA_V_MOROZILNOY_KAMERE",
			37 => "SHIRINA",
			38 => "VYSOTA",
			39 => "GLUBINA",
			40 => "DIAGONAL_SM",
			41 => "PODDERZHKA_USB_V_TELEVIZORE",
			42 => "PODDERZHKA_MP3",
			43 => "PODDERZHKA_DVD",
			44 => "PODDERZHKA_USB",
			45 => "CHISLO_MEGAPIKSELEY",
			46 => "SERTIFIKAT",
			47 => "TIP_UBORKI",
			48 => "TIP_PYLESBORNIKA",
			49 => "VES_VYPECHKI_G",
			50 => "KOLICHESTVO_PROGRAMM_KHLEBOPECHI",
			51 => "TIP_UPRAVLENIYA_MULTIVARKI",
			52 => "KOLICHESTVO_PROGRAMM_MULTIVARKI",
			53 => "TIP_UPRAVLENIYA_PAROVARKI",
			54 => "VOZMOZHNOST_DOLIVA_VODY",
			55 => "KOLICHESTVO_YARUSOV",
			56 => "POKRYTIE",
			57 => "PAR",
			58 => "KOLICHESTVO_SKOROSTEY",
			59 => "KOLICHESTVO_TEMPERATURNYKH_REZHIMOV",
			60 => "REZHIM_OKHLAZHDENIYA",
			61 => "IMPULSNYY_REZHIM",
			62 => "MOSHCHNOST_YOGURTNITSY_VT",
			63 => "OBSHCHEE_KOLICHESTVO_PRODUKTA_G",
			64 => "SISTEMA_PITANIYA",
			65 => "POKRYTIE_SHCHIPTSOV",
			66 => "PROIZVODITELNOST_KUB_M_CH",
			67 => "NEWPRODUCT",
			68 => "MANUFACTURER",
			69 => "MATERIAL",
			70 => "",
		),
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_DISPLAY_NAME" => "N",
		"DETAIL_DETAIL_PICTURE_MODE" => "IMG",
		"DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_IBLOCK_ID" => "",
		"LINK_PROPERTY_SID" => "",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"USE_ALSO_BUY" => "N",
		"USE_STORE" => "Y",
		"PAGER_TEMPLATE" => "modern",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
		"PAGER_SHOW_ALL" => "N",
		"TEMPLATE_THEME" => "site",
		"ADD_PICT_PROP" => "-",
		"LABEL_PROP" => "-",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		"DETAIL_SHOW_MAX_QUANTITY" => "N",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"DETAIL_USE_VOTE_RATING" => "Y",
		"DETAIL_VOTE_DISPLAY_AS_RATING" => "rating",
		"DETAIL_USE_COMMENTS" => "Y",
		"DETAIL_BLOG_USE" => "N",
		"DETAIL_VK_USE" => "N",
		"DETAIL_FB_USE" => "N",
		"DETAIL_FB_APP_ID" => "",
		"DETAIL_BRAND_USE" => "Y",
		"DETAIL_BRAND_PROP_CODE" => "-",
		"AJAX_OPTION_ADDITIONAL" => "",
		"FILTER_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"OFFERS_CART_PROPERTIES" => array(
		),
		"LIST_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_OFFERS_LIMIT" => "5",
		"DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "PODDERZHKA",
			1 => "DVD",
			2 => "RAZMER_MATRITSY_MP",
			3 => "MP3",
			4 => "CML2_ARTICLE",
			5 => "CML2_BASE_UNIT",
			6 => "MORE_PHOTO",
			7 => "CML2_MANUFACTURER",
			8 => "CML2_TRAITS",
			9 => "CML2_TAXES",
			10 => "TIP_ZAGRUZKI",
			11 => "FILES",
			12 => "CML2_ATTRIBUTES",
			13 => "CML2_BAR_CODE",
			14 => "VES_ZAGRUZHAEMOGO_BELYA",
			15 => "TIP_SUSHKI",
			16 => "KOLICHESTVO_KOMPLEKTOV_SHT",
			17 => "GRIL",
			18 => "KONVEKTSIYA",
			19 => "KOLICHESTVO_KONFOROK",
			20 => "ELEKTROPODZHIG",
			21 => "DUKHOVKA",
			22 => "TIP_VAROCHNOY_POVERKHNOSTI",
			23 => "TIP_UPRAVLENIYA_MIKROVOLNOVOY_PECHI",
			24 => "MOSHCHNOST_MIKROVOLN_GRILYA_VT",
			25 => "REZHIM_OBOGREVA",
			26 => "SPOSOB_NAGREVA",
			27 => "TIP_OBOGREVATELYA",
			28 => "TIP_VODONAGREVATELYA",
			29 => "TIP",
			30 => "MOSHCHNOST_VT",
			31 => "STRANA_PROIZVODITEL",
			32 => "BREND",
			33 => "TSVET",
			34 => "OBYEM_L",
			35 => "OBYEM_KHOLODILNOY_KAMERY_L",
			36 => "OBYEM_MOROZILNOY_KAMERY_L",
			37 => "KOLICHESTVO_KOMPRESSOROV",
			38 => "TIP_RAZMORAZHIVANIYA_KHOLODILNOY_KAMERY",
			39 => "TIP_RAZMORAZHIVANIYA_MOROZILNOY_KAMERY",
			40 => "KLASS_ENERGOPOTREBLENIYA",
			41 => "TEMPERATURA_V_MOROZILNOY_KAMERE",
			42 => "SHIRINA",
			43 => "VYSOTA",
			44 => "GLUBINA",
			45 => "DIAGONAL_SM",
			46 => "PODDERZHKA_USB_V_TELEVIZORE",
			47 => "PODDERZHKA_MP3",
			48 => "PODDERZHKA_DVD",
			49 => "PODDERZHKA_USB",
			50 => "CHISLO_MEGAPIKSELEY",
			51 => "SERTIFIKAT",
			52 => "TIP_UBORKI",
			53 => "TIP_PYLESBORNIKA",
			54 => "VES_VYPECHKI_G",
			55 => "KOLICHESTVO_PROGRAMM_KHLEBOPECHI",
			56 => "TIP_UPRAVLENIYA_MULTIVARKI",
			57 => "KOLICHESTVO_PROGRAMM_MULTIVARKI",
			58 => "TIP_UPRAVLENIYA_PAROVARKI",
			59 => "VOZMOZHNOST_DOLIVA_VODY",
			60 => "KOLICHESTVO_YARUSOV",
			61 => "POKRYTIE",
			62 => "PAR",
			63 => "KOLICHESTVO_SKOROSTEY",
			64 => "KOLICHESTVO_TEMPERATURNYKH_REZHIMOV",
			65 => "REZHIM_OKHLAZHDENIYA",
			66 => "IMPULSNYY_REZHIM",
			67 => "MOSHCHNOST_YOGURTNITSY_VT",
			68 => "OBSHCHEE_KOLICHESTVO_PRODUKTA_G",
			69 => "SISTEMA_PITANIYA",
			70 => "POKRYTIE_SHCHIPTSOV",
			71 => "PROIZVODITELNOST_KUB_M_CH",
			72 => "",
		),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "desc",
		"PRODUCT_DISPLAY_MODE" => "N",
		"OFFER_ADD_PICT_PROP" => "-",
		"OFFER_TREE_PROPS" => array(
		),
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"COMPARE_FIELD_CODE" => array(
			0 => "ID",
			1 => "CODE",
			2 => "XML_ID",
			3 => "NAME",
			4 => "TAGS",
			5 => "SORT",
			6 => "",
		),
		"COMPARE_PROPERTY_CODE" => array(
			0 => "PODDERZHKA",
			1 => "DVD",
			2 => "RAZMER_MATRITSY_MP",
			3 => "MP3",
			4 => "BLOG_POST_ID",
			5 => "CML2_ARTICLE",
			6 => "CML2_BASE_UNIT",
			7 => "F_USER",
			8 => "BLOG_COMMENTS_CNT",
			9 => "FORUM_MESSAGE_CNT",
			10 => "vote_count",
			11 => "CML2_MANUFACTURER",
			12 => "rating",
			13 => "CML2_TRAITS",
			14 => "SORTDISCOUNT",
			15 => "CML2_TAXES",
			16 => "vote_sum",
			17 => "FORUM_TOPIC_ID",
			18 => "TIP_ZAGRUZKI",
			19 => "daygood",
			20 => "CML2_ATTRIBUTES",
			21 => "HIT",
			22 => "",
		),
		"COMPARE_OFFERS_FIELD_CODE" => array(
			0 => "ID",
			1 => "",
		),
		"COMPARE_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"COMPARE_ELEMENT_SORT_FIELD" => "sort",
		"COMPARE_ELEMENT_SORT_ORDER" => "asc",
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",
		"MESSAGES_PER_PAGE" => "10",
		"USE_CAPTCHA" => "Y",
		"REVIEW_AJAX_POST" => "Y",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"FORUM_ID" => "1",
		"URL_TEMPLATES_READ" => "",
		"SHOW_LINK_TO_FORUM" => "N",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"STORES" => array(
			0 => "1",
		),
		"USE_MIN_AMOUNT" => "Y",
		"USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"FIELDS" => array(
			0 => "",
			1 => "",
		),
		"MIN_AMOUNT" => "3",
		"SHOW_EMPTY_STORE" => "Y",
		"SHOW_GENERAL_STORE_INFORMATION" => "Y",
		"STORE_PATH" => "/store/#store_id#",
		"MAIN_TITLE" => "Наличие на складах",
		"COMPONENT_TEMPLATE" => "template1",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SECTION_BACKGROUND_IMAGE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_BACKGROUND_IMAGE" => "-",
		"SHOW_DEACTIVATED" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DETAIL_SET_VIEWED_IN_COMPONENT" => "N",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "/catalog/",
			"section" => "#SECTION_CODE_PATH#/",
			"element" => "#SECTION_CODE_PATH#/#ELEMENT_ID#/",
			"compare" => "/catalog/compare/",
			"smart_filter" => "#SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/",
		)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>