<?$APPLICATION->IncludeComponent(
	"aspro:catalog.section.list.optimus",
	"front_sections_only",
	array(
		"IBLOCK_TYPE" => "aspro_optimus_catalog",
		"IBLOCK_ID" => \Bitrix\Main\Config\Option::get("aspro.optimus", "CATALOG_IBLOCK_ID", "29"),
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"COUNT_ELEMENTS" => "N",
		"FILTER_NAME" => "arBrandSections",
		"TOP_DEPTH" => $arParams["DEPTH_LEVEL_BRAND"],
		"SECTION_URL" => "",
		"VIEW_MODE" => "",
		"SHOW_PARENT_NAME" => "N",
		"HIDE_SECTION_NAME" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"USE_FILTER_SECTION" => "Y",
		"BRAND_NAME" => $arResult["NAME"],
		"BRAND_CODE" => $templateData["CODE"],
		"SHOW_SECTIONS_LIST_PREVIEW" => "N",
		"SECTIONS_LIST_PREVIEW_PROPERTY" => "N",
		"SECTIONS_LIST_PREVIEW_DESCRIPTION" => "N",
		"SHOW_SECTION_LIST_PICTURES" => "N",
		"DISPLAY_PANEL" => "N",
		"COMPONENT_TEMPLATE" => "front_sections_only",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"SECTION_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
	),
	false, array("HIDE_ICONS" => "Y")
);?>